/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.blf.calendar;

public class CGPoint {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CGPoint(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CGPoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        calendarCoreJNI.delete_CGPoint(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(float value) {
    calendarCoreJNI.CGPoint_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return calendarCoreJNI.CGPoint_x_get(swigCPtr, this);
  }

  public void setY(float value) {
    calendarCoreJNI.CGPoint_y_set(swigCPtr, this, value);
  }

  public float getY() {
    return calendarCoreJNI.CGPoint_y_get(swigCPtr, this);
  }

  public CGPoint() {
    this(calendarCoreJNI.new_CGPoint(), true);
  }

}
