/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.blf.calendar;

public class SDate {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SDate(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDate obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        calendarCoreJNI.delete_SDate(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setYear(int value) {
    calendarCoreJNI.SDate_year_set(swigCPtr, this, value);
  }

  public int getYear() {
    return calendarCoreJNI.SDate_year_get(swigCPtr, this);
  }

  public void setMonth(int value) {
    calendarCoreJNI.SDate_month_set(swigCPtr, this, value);
  }

  public int getMonth() {
    return calendarCoreJNI.SDate_month_get(swigCPtr, this);
  }

  public void setDay(int value) {
    calendarCoreJNI.SDate_day_set(swigCPtr, this, value);
  }

  public int getDay() {
    return calendarCoreJNI.SDate_day_get(swigCPtr, this);
  }

  public SDate() {
    this(calendarCoreJNI.new_SDate(), true);
  }

}
