/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.blf.calendar;

public class calendarCore {
  public static void date_set(SDate date, int year, int month, int day) {
    calendarCoreJNI.date_set(SDate.getCPtr(date), date, year, month, day);
  }

  public static void date_get_now(SDate date) {
    calendarCoreJNI.date_get_now(SDate.getCPtr(date), date);
  }

  public static boolean date_is_equal(SDate left, SDate right) {
    return calendarCoreJNI.date_is_equal(SDate.getCPtr(left), left, SDate.getCPtr(right), right);
  }

  public static int date_get_time_t(SDate d) {
    return calendarCoreJNI.date_get_time_t(SDate.getCPtr(d), d);
  }

  public static void date_get_next_month(SDate date, int delta) {
    calendarCoreJNI.date_get_next_month(SDate.getCPtr(date), date, delta);
  }

  public static void date_get_prev_month(SDate date, int delta) {
    calendarCoreJNI.date_get_prev_month(SDate.getCPtr(date), date, delta);
  }

  public static int date_get_week(SDate date) {
    return calendarCoreJNI.date_get_week(SDate.getCPtr(date), date);
  }

  public static int date_get_month_of_day(int year, int month) {
    return calendarCoreJNI.date_get_month_of_day(year, month);
  }

  public static int date_get_leap(int year) {
    return calendarCoreJNI.date_get_leap(year);
  }

  public static int date_get_month_count_from_year_range(int startYear, int endYear) {
    return calendarCoreJNI.date_get_month_count_from_year_range(startYear, endYear);
  }

  public static void date_map_index_to_year_month(SDate to, int startYear, int idx) {
    calendarCoreJNI.date_map_index_to_year_month(SDate.getCPtr(to), to, startYear, idx);
  }

  public static void calendar_init(SCalendar calendar, CGSize ownerSize, float yearMonthHeight, float weekHeight) {
    calendarCoreJNI.calendar_init(SCalendar.getCPtr(calendar), calendar, CGSize.getCPtr(ownerSize), ownerSize, yearMonthHeight, weekHeight);
  }

  public static void calendar_set_year_month(SCalendar calendar, int year, int month) {
    calendarCoreJNI.calendar_set_year_month(SCalendar.getCPtr(calendar), calendar, year, month);
  }

  public static void calendar_get_year_month(SCalendar calendar, SWIGTYPE_p_int year, SWIGTYPE_p_int month) {
    calendarCoreJNI.calendar_get_year_month(SCalendar.getCPtr(calendar), calendar, SWIGTYPE_p_int.getCPtr(year), SWIGTYPE_p_int.getCPtr(month));
  }

  public static void calendar_get_year_month_section_rect(SCalendar calendar, CGRect rect) {
    calendarCoreJNI.calendar_get_year_month_section_rect(SCalendar.getCPtr(calendar), calendar, CGRect.getCPtr(rect), rect);
  }

  public static void calendar_get_week_section_rect(SCalendar calendar, CGRect rect) {
    calendarCoreJNI.calendar_get_week_section_rect(SCalendar.getCPtr(calendar), calendar, CGRect.getCPtr(rect), rect);
  }

  public static void calendar_get_day_section_rect(SCalendar calendar, CGRect rect) {
    calendarCoreJNI.calendar_get_day_section_rect(SCalendar.getCPtr(calendar), calendar, CGRect.getCPtr(rect), rect);
  }

  public static void calendar_get_week_cell_rect(SCalendar calendar, CGRect rect, int idx) {
    calendarCoreJNI.calendar_get_week_cell_rect(SCalendar.getCPtr(calendar), calendar, CGRect.getCPtr(rect), rect, idx);
  }

  public static void calendar_get_day_cell_rect(SCalendar calendar, CGRect rect, int rowIdx, int columIdx) {
    calendarCoreJNI.calendar_get_day_cell_rect(SCalendar.getCPtr(calendar), calendar, CGRect.getCPtr(rect), rect, rowIdx, columIdx);
  }

  public static void calendar_get_day_cell_rect_by_index(SCalendar calendar, CGRect rect, int idx) {
    calendarCoreJNI.calendar_get_day_cell_rect_by_index(SCalendar.getCPtr(calendar), calendar, CGRect.getCPtr(rect), rect, idx);
  }

  public static int calendar_get_hitted_day_cell_index(SCalendar calendar, CGPoint localPt) {
    return calendarCoreJNI.calendar_get_hitted_day_cell_index(SCalendar.getCPtr(calendar), calendar, CGPoint.getCPtr(localPt), localPt);
  }

}
