/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.blf.calendar;

public class CGRect {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CGRect(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CGRect obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        calendarCoreJNI.delete_CGRect(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setOrigin(CGPoint value) {
    calendarCoreJNI.CGRect_origin_set(swigCPtr, this, CGPoint.getCPtr(value), value);
  }

  public CGPoint getOrigin() {
    long cPtr = calendarCoreJNI.CGRect_origin_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CGPoint(cPtr, false);
  }

  public void setSize(CGSize value) {
    calendarCoreJNI.CGRect_size_set(swigCPtr, this, CGSize.getCPtr(value), value);
  }

  public CGSize getSize() {
    long cPtr = calendarCoreJNI.CGRect_size_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CGSize(cPtr, false);
  }

  public CGRect() {
    this(calendarCoreJNI.new_CGRect(), true);
  }

}
