/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.blf.calendar;

public class CGSize {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CGSize(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CGSize obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        calendarCoreJNI.delete_CGSize(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setWidth(float value) {
    calendarCoreJNI.CGSize_width_set(swigCPtr, this, value);
  }

  public float getWidth() {
    return calendarCoreJNI.CGSize_width_get(swigCPtr, this);
  }

  public void setHeight(float value) {
    calendarCoreJNI.CGSize_height_set(swigCPtr, this, value);
  }

  public float getHeight() {
    return calendarCoreJNI.CGSize_height_get(swigCPtr, this);
  }

  public CGSize() {
    this(calendarCoreJNI.new_CGSize(), true);
  }

}
