/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.blf.calendar;

public class SCalendar {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SCalendar(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SCalendar obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        calendarCoreJNI.delete_SCalendar(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSize(CGSize value) {
    calendarCoreJNI.SCalendar_size_set(swigCPtr, this, CGSize.getCPtr(value), value);
  }

  public CGSize getSize() {
    long cPtr = calendarCoreJNI.SCalendar_size_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CGSize(cPtr, false);
  }

  public void setDate(SDate value) {
    calendarCoreJNI.SCalendar_date_set(swigCPtr, this, SDate.getCPtr(value), value);
  }

  public SDate getDate() {
    long cPtr = calendarCoreJNI.SCalendar_date_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDate(cPtr, false);
  }

  public void setYearMonthSectionHeight(float value) {
    calendarCoreJNI.SCalendar_yearMonthSectionHeight_set(swigCPtr, this, value);
  }

  public float getYearMonthSectionHeight() {
    return calendarCoreJNI.SCalendar_yearMonthSectionHeight_get(swigCPtr, this);
  }

  public void setWeekSectionHegiht(float value) {
    calendarCoreJNI.SCalendar_weekSectionHegiht_set(swigCPtr, this, value);
  }

  public float getWeekSectionHegiht() {
    return calendarCoreJNI.SCalendar_weekSectionHegiht_get(swigCPtr, this);
  }

  public void setDaySectionHeight(float value) {
    calendarCoreJNI.SCalendar_daySectionHeight_set(swigCPtr, this, value);
  }

  public float getDaySectionHeight() {
    return calendarCoreJNI.SCalendar_daySectionHeight_get(swigCPtr, this);
  }

  public void setDayBeginIdx(int value) {
    calendarCoreJNI.SCalendar_dayBeginIdx_set(swigCPtr, this, value);
  }

  public int getDayBeginIdx() {
    return calendarCoreJNI.SCalendar_dayBeginIdx_get(swigCPtr, this);
  }

  public void setDayCount(int value) {
    calendarCoreJNI.SCalendar_dayCount_set(swigCPtr, this, value);
  }

  public int getDayCount() {
    return calendarCoreJNI.SCalendar_dayCount_get(swigCPtr, this);
  }

  public SCalendar() {
    this(calendarCoreJNI.new_SCalendar(), true);
  }

}
