/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif



#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  jenv->ExceptionClear();
  excep = jenv->FindClass(except_ptr->java_exception);
  if (excep)
    jenv->ThrowNew(excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


 /* Includes the header in the wrapper code */
#include "calendarCore.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_CGPoint_1x_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2) {
  _CGPoint *arg1 = (_CGPoint *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_CGPoint **)&jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->x = arg2;
}


SWIGEXPORT jfloat JNICALL Java_com_blf_calendar_calendarCoreJNI_CGPoint_1x_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  _CGPoint *arg1 = (_CGPoint *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_CGPoint **)&jarg1; 
  result = (float) ((arg1)->x);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_CGPoint_1y_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2) {
  _CGPoint *arg1 = (_CGPoint *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_CGPoint **)&jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->y = arg2;
}


SWIGEXPORT jfloat JNICALL Java_com_blf_calendar_calendarCoreJNI_CGPoint_1y_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  _CGPoint *arg1 = (_CGPoint *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_CGPoint **)&jarg1; 
  result = (float) ((arg1)->y);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_blf_calendar_calendarCoreJNI_new_1CGPoint(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  _CGPoint *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (_CGPoint *)new _CGPoint();
  *(_CGPoint **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_delete_1CGPoint(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  _CGPoint *arg1 = (_CGPoint *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(_CGPoint **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_CGSize_1width_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2) {
  _CGSize *arg1 = (_CGSize *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_CGSize **)&jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->width = arg2;
}


SWIGEXPORT jfloat JNICALL Java_com_blf_calendar_calendarCoreJNI_CGSize_1width_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  _CGSize *arg1 = (_CGSize *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_CGSize **)&jarg1; 
  result = (float) ((arg1)->width);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_CGSize_1height_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2) {
  _CGSize *arg1 = (_CGSize *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_CGSize **)&jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->height = arg2;
}


SWIGEXPORT jfloat JNICALL Java_com_blf_calendar_calendarCoreJNI_CGSize_1height_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  _CGSize *arg1 = (_CGSize *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_CGSize **)&jarg1; 
  result = (float) ((arg1)->height);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_blf_calendar_calendarCoreJNI_new_1CGSize(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  _CGSize *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (_CGSize *)new _CGSize();
  *(_CGSize **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_delete_1CGSize(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  _CGSize *arg1 = (_CGSize *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(_CGSize **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_CGRect_1origin_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  _CGRect *arg1 = (_CGRect *) 0 ;
  CGPoint *arg2 = (CGPoint *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(_CGRect **)&jarg1; 
  arg2 = *(CGPoint **)&jarg2; 
  if (arg1) (arg1)->origin = *arg2;
}


SWIGEXPORT jlong JNICALL Java_com_blf_calendar_calendarCoreJNI_CGRect_1origin_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  _CGRect *arg1 = (_CGRect *) 0 ;
  CGPoint *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_CGRect **)&jarg1; 
  result = (CGPoint *)& ((arg1)->origin);
  *(CGPoint **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_CGRect_1size_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  _CGRect *arg1 = (_CGRect *) 0 ;
  CGSize *arg2 = (CGSize *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(_CGRect **)&jarg1; 
  arg2 = *(CGSize **)&jarg2; 
  if (arg1) (arg1)->size = *arg2;
}


SWIGEXPORT jlong JNICALL Java_com_blf_calendar_calendarCoreJNI_CGRect_1size_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  _CGRect *arg1 = (_CGRect *) 0 ;
  CGSize *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_CGRect **)&jarg1; 
  result = (CGSize *)& ((arg1)->size);
  *(CGSize **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_blf_calendar_calendarCoreJNI_new_1CGRect(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  _CGRect *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (_CGRect *)new _CGRect();
  *(_CGRect **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_delete_1CGRect(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  _CGRect *arg1 = (_CGRect *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(_CGRect **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_SDate_1year_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  _date *arg1 = (_date *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_date **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->year = arg2;
}


SWIGEXPORT jint JNICALL Java_com_blf_calendar_calendarCoreJNI_SDate_1year_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  _date *arg1 = (_date *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_date **)&jarg1; 
  result = (int) ((arg1)->year);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_SDate_1month_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  _date *arg1 = (_date *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_date **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->month = arg2;
}


SWIGEXPORT jint JNICALL Java_com_blf_calendar_calendarCoreJNI_SDate_1month_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  _date *arg1 = (_date *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_date **)&jarg1; 
  result = (int) ((arg1)->month);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_SDate_1day_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  _date *arg1 = (_date *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_date **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->day = arg2;
}


SWIGEXPORT jint JNICALL Java_com_blf_calendar_calendarCoreJNI_SDate_1day_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  _date *arg1 = (_date *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_date **)&jarg1; 
  result = (int) ((arg1)->day);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_blf_calendar_calendarCoreJNI_new_1SDate(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  _date *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (_date *)new _date();
  *(_date **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_delete_1SDate(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  _date *arg1 = (_date *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(_date **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_date_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jint jarg3, jint jarg4) {
  SDate *arg1 = (SDate *) 0 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SDate **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  date_set(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_date_1get_1now(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  SDate *arg1 = (SDate *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SDate **)&jarg1; 
  date_get_now(arg1);
}


SWIGEXPORT jboolean JNICALL Java_com_blf_calendar_calendarCoreJNI_date_1is_1equal(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jboolean jresult = 0 ;
  SDate *arg1 = (SDate *) 0 ;
  SDate *arg2 = (SDate *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(SDate **)&jarg1; 
  arg2 = *(SDate **)&jarg2; 
  result = (bool)date_is_equal((_date const *)arg1,(_date const *)arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_blf_calendar_calendarCoreJNI_date_1get_1time_1t(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  SDate *arg1 = (SDate *) 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SDate **)&jarg1; 
  result = (long)date_get_time_t((_date const *)arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_date_1get_1next_1month(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  SDate *arg1 = (SDate *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SDate **)&jarg1; 
  arg2 = (int)jarg2; 
  date_get_next_month(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_date_1get_1prev_1month(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  SDate *arg1 = (SDate *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SDate **)&jarg1; 
  arg2 = (int)jarg2; 
  date_get_prev_month(arg1,arg2);
}


SWIGEXPORT jint JNICALL Java_com_blf_calendar_calendarCoreJNI_date_1get_1week(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  SDate *arg1 = (SDate *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SDate **)&jarg1; 
  result = (int)date_get_week((_date const *)arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_blf_calendar_calendarCoreJNI_date_1get_1month_1of_1day(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  jint jresult = 0 ;
  int arg1 ;
  int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  result = (int)date_get_month_of_day(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_blf_calendar_calendarCoreJNI_date_1get_1leap(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jint jresult = 0 ;
  int arg1 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (int)date_get_leap(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_blf_calendar_calendarCoreJNI_date_1get_1month_1count_1from_1year_1range(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  jint jresult = 0 ;
  int arg1 ;
  int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  result = (int)date_get_month_count_from_year_range(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_date_1map_1index_1to_1year_1month(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jint jarg3) {
  SDate *arg1 = (SDate *) 0 ;
  int arg2 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SDate **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  date_map_index_to_year_month(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_SCalendar_1size_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  _calendar *arg1 = (_calendar *) 0 ;
  CGSize *arg2 = (CGSize *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(_calendar **)&jarg1; 
  arg2 = *(CGSize **)&jarg2; 
  if (arg1) (arg1)->size = *arg2;
}


SWIGEXPORT jlong JNICALL Java_com_blf_calendar_calendarCoreJNI_SCalendar_1size_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  _calendar *arg1 = (_calendar *) 0 ;
  CGSize *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_calendar **)&jarg1; 
  result = (CGSize *)& ((arg1)->size);
  *(CGSize **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_SCalendar_1date_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  _calendar *arg1 = (_calendar *) 0 ;
  SDate *arg2 = (SDate *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(_calendar **)&jarg1; 
  arg2 = *(SDate **)&jarg2; 
  if (arg1) (arg1)->date = *arg2;
}


SWIGEXPORT jlong JNICALL Java_com_blf_calendar_calendarCoreJNI_SCalendar_1date_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  _calendar *arg1 = (_calendar *) 0 ;
  SDate *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_calendar **)&jarg1; 
  result = (SDate *)& ((arg1)->date);
  *(SDate **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_SCalendar_1yearMonthSectionHeight_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2) {
  _calendar *arg1 = (_calendar *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_calendar **)&jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->yearMonthSectionHeight = arg2;
}


SWIGEXPORT jfloat JNICALL Java_com_blf_calendar_calendarCoreJNI_SCalendar_1yearMonthSectionHeight_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  _calendar *arg1 = (_calendar *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_calendar **)&jarg1; 
  result = (float) ((arg1)->yearMonthSectionHeight);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_SCalendar_1weekSectionHegiht_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2) {
  _calendar *arg1 = (_calendar *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_calendar **)&jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->weekSectionHegiht = arg2;
}


SWIGEXPORT jfloat JNICALL Java_com_blf_calendar_calendarCoreJNI_SCalendar_1weekSectionHegiht_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  _calendar *arg1 = (_calendar *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_calendar **)&jarg1; 
  result = (float) ((arg1)->weekSectionHegiht);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_SCalendar_1daySectionHeight_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2) {
  _calendar *arg1 = (_calendar *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_calendar **)&jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->daySectionHeight = arg2;
}


SWIGEXPORT jfloat JNICALL Java_com_blf_calendar_calendarCoreJNI_SCalendar_1daySectionHeight_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  _calendar *arg1 = (_calendar *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_calendar **)&jarg1; 
  result = (float) ((arg1)->daySectionHeight);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_SCalendar_1dayBeginIdx_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  _calendar *arg1 = (_calendar *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_calendar **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->dayBeginIdx = arg2;
}


SWIGEXPORT jint JNICALL Java_com_blf_calendar_calendarCoreJNI_SCalendar_1dayBeginIdx_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  _calendar *arg1 = (_calendar *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_calendar **)&jarg1; 
  result = (int) ((arg1)->dayBeginIdx);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_SCalendar_1dayCount_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  _calendar *arg1 = (_calendar *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_calendar **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->dayCount = arg2;
}


SWIGEXPORT jint JNICALL Java_com_blf_calendar_calendarCoreJNI_SCalendar_1dayCount_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  _calendar *arg1 = (_calendar *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_calendar **)&jarg1; 
  result = (int) ((arg1)->dayCount);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_blf_calendar_calendarCoreJNI_new_1SCalendar(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  _calendar *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (_calendar *)new _calendar();
  *(_calendar **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_delete_1SCalendar(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  _calendar *arg1 = (_calendar *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(_calendar **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_calendar_1init(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jfloat jarg3, jfloat jarg4) {
  SCalendar *arg1 = (SCalendar *) 0 ;
  CGSize arg2 ;
  float arg3 ;
  float arg4 ;
  CGSize *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(SCalendar **)&jarg1; 
  argp2 = *(CGSize **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null CGSize");
    return ;
  }
  arg2 = *argp2; 
  arg3 = (float)jarg3; 
  arg4 = (float)jarg4; 
  calendar_init(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_calendar_1set_1year_1month(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jint jarg3) {
  SCalendar *arg1 = (SCalendar *) 0 ;
  int arg2 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SCalendar **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  calendar_set_year_month(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_calendar_1get_1year_1month(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3) {
  SCalendar *arg1 = (SCalendar *) 0 ;
  int *arg2 = (int *) 0 ;
  int *arg3 = (int *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SCalendar **)&jarg1; 
  arg2 = *(int **)&jarg2; 
  arg3 = *(int **)&jarg3; 
  calendar_get_year_month(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_calendar_1get_1year_1month_1section_1rect(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  SCalendar *arg1 = (SCalendar *) 0 ;
  CGRect *arg2 = (CGRect *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(SCalendar **)&jarg1; 
  arg2 = *(CGRect **)&jarg2; 
  calendar_get_year_month_section_rect((_calendar const *)arg1,arg2);
}


SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_calendar_1get_1week_1section_1rect(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  SCalendar *arg1 = (SCalendar *) 0 ;
  CGRect *arg2 = (CGRect *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(SCalendar **)&jarg1; 
  arg2 = *(CGRect **)&jarg2; 
  calendar_get_week_section_rect((_calendar const *)arg1,arg2);
}


SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_calendar_1get_1day_1section_1rect(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  SCalendar *arg1 = (SCalendar *) 0 ;
  CGRect *arg2 = (CGRect *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(SCalendar **)&jarg1; 
  arg2 = *(CGRect **)&jarg2; 
  calendar_get_day_section_rect((_calendar const *)arg1,arg2);
}


SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_calendar_1get_1week_1cell_1rect(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jint jarg3) {
  SCalendar *arg1 = (SCalendar *) 0 ;
  CGRect *arg2 = (CGRect *) 0 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(SCalendar **)&jarg1; 
  arg2 = *(CGRect **)&jarg2; 
  arg3 = (int)jarg3; 
  calendar_get_week_cell_rect((_calendar const *)arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_calendar_1get_1day_1cell_1rect(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jint jarg3, jint jarg4) {
  SCalendar *arg1 = (SCalendar *) 0 ;
  CGRect *arg2 = (CGRect *) 0 ;
  int arg3 ;
  int arg4 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(SCalendar **)&jarg1; 
  arg2 = *(CGRect **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  calendar_get_day_cell_rect((_calendar const *)arg1,arg2,arg3,arg4);
}


SWIGEXPORT void JNICALL Java_com_blf_calendar_calendarCoreJNI_calendar_1get_1day_1cell_1rect_1by_1index(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jint jarg3) {
  SCalendar *arg1 = (SCalendar *) 0 ;
  CGRect *arg2 = (CGRect *) 0 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(SCalendar **)&jarg1; 
  arg2 = *(CGRect **)&jarg2; 
  arg3 = (int)jarg3; 
  calendar_get_day_cell_rect_by_index((_calendar const *)arg1,arg2,arg3);
}


SWIGEXPORT jint JNICALL Java_com_blf_calendar_calendarCoreJNI_calendar_1get_1hitted_1day_1cell_1index(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jint jresult = 0 ;
  SCalendar *arg1 = (SCalendar *) 0 ;
  CGPoint arg2 ;
  CGPoint *argp2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(SCalendar **)&jarg1; 
  argp2 = *(CGPoint **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null CGPoint");
    return 0;
  }
  arg2 = *argp2; 
  result = (int)calendar_get_hitted_day_cell_index((_calendar const *)arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

